### PR TITLE
TASK: Modernize code and bump dependencies

### PR DESCRIPTION
**Pull request by Sebobo**
What has changed:

* Use latest React, TypeScript, Parcel, etc...
* Target modern browsers
* Reduce bundle size from 450KB to 350KB
* Require at least Neos 7.3 and PHP 7.3
* Use yarn workspaces
* Use "Lite" stylesheet from Neos
* Adjust resource inclusion setting to allow additional resources via settings
* Update linting and resolve issues
* Apply PHP code cleanup hints to controller

### CODE REVIEW

**Comment by Sebobo** [comment]
We should define a new minor version when this is released as it's not breaking but has bumped dependencies.

**Comment by Sebobo** [comment]
The largest part of the bundle are `react-com` and the `react-datepicker`. I don't know right now how to reduce this further.

**Review by jonnitto — APPROVED** [review]
Tested it and it works

**Review by ahaeslich — COMMENTED** [review]
The linter check fails in `_add-redirect-form.css` on line 59. The import of `@import "../vendor/datepicker";` seems a bit odd.

@Sebobo can we delete this or do we have to include something else?

**Comment by crydotsnake** [comment]
Sry for my missing review so far. Will take a look at the PR this evening!

**Review by crydotsnake — APPROVED** [review]
Tested, and it works!

**Comment by Sebobo** [comment]
> The linter check fails in `_add-redirect-form.css` on line 59. The import of `@import "../vendor/datepicker";` seems a bit odd.
> 
> @Sebobo can we delete this or do we have to include something else?

There was a reason due to specificity. So I disabled the style lint rule.

**Pull request merged**
