### PR TITLE
TASK: declare compatibility to Neos 9

### PR DESCRIPTION
**Pull request by ahaeslich**

### CODE REVIEW

**Comment by dlubitz** [comment]
For all other redirect packages, we released a new major just for 9.0 and with strengthened constrains to PHP8.2. Shoudn't we do the same here?

See e.g https://github.com/neos/redirecthandler/pull/61/files

**Comment by ahaeslich** [comment]
Thx. I missed that.

**Review by dlubitz — APPROVED** [review]

**Comment by ahaeslich** [comment]
@Sebobo I just saw that we didn't release your refactoring and #93. Before we merge this and create a 9.x only releas: did you plan for a new 8.x compatible release?

**Comment by ahaeslich** [comment]
Just talk with @Sebobo and will release a 2.5.0 before we merge this one and drop older neos versions.

**Pull request merged**
