### PR TITLE
BUGFIX: Move redirects JSON to script tag

### PR DESCRIPTION
**Pull request by gradinarufelix**
See #82. I moved the redirects JSON to a separate script tag as the data attribute seems not to work beyond a certain size. Can someone please check this in his own installation as well?

### CODE REVIEW

**Comment by Sebobo** [comment]
@gradinarufelix awesome thx, can you remove the compiled js and source map from the PR? 
We only recreate them for releases.

**Comment by Sebobo** [comment]
How many redirects did you have when the error occurred?

**Comment by Sebobo** [comment]
Cherry picked the actual change now and made a new release. Thx for your contribution <3

**Comment by gradinarufelix** [comment]
Ah sorry, didn't see your comments. Thanks for merging! <3

**Pull request closed without merging**
