### PR TITLE
TASK: Improve UX by improved color coding and preventing small mistakes

### PR DESCRIPTION
**Pull request by Sebobo**
Sometimes people enter an asterisk as source host which causes a redirect not to work. With this change these asterisks are simply replaced with an empty value.

Also Redirects that apply to any domain are color coded in the host field.
Expired redirects and ones that are not active yet have also improved color coding.

redirect-ui-labels

### CODE REVIEW

**Comment by Sebobo** [comment]
I'm still adding and optimising some things

**Comment by Sebobo** [comment]
Hi @jonnitto, I think with this state we could process for now, what do you think?

**Comment by jonnitto** [comment]
image

One small thing: We have a mark (`*`) that the field is required, but this is nowhere explained…

**Comment by Sebobo** [comment]
I think people know. And nobody complained so far.

**Pull request merged**
